/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#111319',
        'surface-dim': '#111319',
        'surface-bright': '#373940',
        'surface-container-lowest': '#0c0e14',
        'surface-container-low': '#191b22',
        'surface-container': '#1e1f26',
        'surface-container-high': '#282a30',
        'surface-container-highest': '#33343b',
        'surface-variant': '#33343b',
        'on-surface': '#e2e2eb',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#e2e2eb',
        'inverse-on-surface': '#2e3037',
        outline: '#849495',
        'outline-variant': '#3b494b',
        'surface-tint': '#00dbe9',
        primary: '#dbfcff',
        'on-primary': '#00363a',
        'primary-container': '#00f0ff',
        'on-primary-container': '#006970',
        'inverse-primary': '#006970',
        'primary-fixed': '#7df4ff',
        'primary-fixed-dim': '#00dbe9',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        secondary: '#ffb86b',
        'secondary-container': '#ed9000',
        'on-secondary': '#492900',
        'on-secondary-container': '#583300',
        'secondary-fixed': '#ffdcbc',
        'secondary-fixed-dim': '#ffb86b',
        'on-secondary-fixed': '#2c1700',
        'on-secondary-fixed-variant': '#683d00',
        tertiary: '#fdf2ff',
        'tertiary-container': '#eacfff',
        'on-tertiary': '#490080',
        'on-tertiary-container': '#842bd2',
        'tertiary-fixed': '#f0dbff',
        'tertiary-fixed-dim': '#ddb7ff',
        'on-tertiary-fixed': '#2c0051',
        'on-tertiary-fixed-variant': '#6900b3',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'signal-green': '#10b981',
        'signal-red': '#ef4444',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        xs: '2px',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.375rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.125rem',
        'space-sm': '0.25rem',
        'space-md': '0.5rem',
        'space-lg': '0.75rem',
        'space-xl': '1rem',
        gutter: '0.5rem',
        'gutter-mobile': '0.25rem',
        margin: '0.75rem',
        'margin-mobile': '0.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'label-lg': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'meter-data': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'meter-data': ['0.625rem', { lineHeight: '0.75rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['0.5625rem', { lineHeight: '0.75rem', letterSpacing: '0.04em', fontWeight: '400' }],
        'label-md': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-lg': ['0.8125rem', { lineHeight: '1rem', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-md': ['0.75rem', { lineHeight: '1.125rem', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-lg': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0em', fontWeight: '400' }],
        'headline-sm': ['1rem', { lineHeight: '1.375rem', letterSpacing: '0em', fontWeight: '500' }],
        'headline-md': ['1.25rem', { lineHeight: '1.625rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        cyan: '0 0 8px rgba(0, 240, 255, 0.45)',
        amber: '0 0 8px rgba(255, 159, 28, 0.45)',
        red: '0 0 8px rgba(239, 68, 68, 0.6)',
      },
    },
  },
  plugins: [],
};
